package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.39

import (
	"context"
	"fmt"

	"github.com/NhanThanhHuynh/gqlgen1/graph/model"
	"github.com/dchest/uniuri"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.UserInput) (*model.User, error) {
	userInput := &model.User{
		ID:   uniuri.New(),
		Name: input.Name,
	}
	fmt.Println(userInput, "userInput")
	return r.Domain.UsersRepo.CreateUser(userInput)
}

// FindUser is the resolver for the findUser field.
func (r *queryResolver) FindUser(ctx context.Context, id string) (*model.User, error) {
	return r.Domain.UsersRepo.GetUserByID(id)
}
