// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type TodoDetailInput struct {
	Text string `json:"text"`
}

type TodoInput struct {
	Text   string `json:"text"`
	Done   bool   `json:"done"`
	UserID string `json:"UserID"`
}

type UserInput struct {
	Name string `json:"name"`
}
